<?php

use Illuminate\Database\Seeder;
use Illuminate\Filesystem\Filesystem;

class RoboAdvisorSeeder extends Seeder
{
    private $robo_advisor_iteration = 0;
    private $account_type_iteration = 0;

    const ROBO_ADVISORS = [
        'WEALTHFRONT' => [
            'name' => 'Wealthfront',
            'logo' => '/files/wealthfront-review.png',
            'title' => 'Wealthfront Review 2018 – Improving on Passive Investing',
            'short_description' => "<p>Wealthfront is a robo advisor that emphasizes low fees and automated investing. The service shines when you have a taxable account, and the service is free for accounts under $5K if you use the Investor Junkie promotion or if you are referred by a current Wealthfront client. The negative is it doesn&#39;t support fractional shares.</p>",
            'description' => null,
            'referral_link' => 'https://www.wealthfront.com/',
            'video_link' => null,
            'minimum_account' => '500',
            'management_fee' => '0.25',
            'fee_details' => 'Free under $10k and SoFi  Borrowers; 0.25%/year',
            'aum' => '11022761706',
            'promotions' => '$5k Managed for Free Exclusive',
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '1',
            'tax_loss' => '1',
            'tax_loss_details' => 'All Taxable Accounts',
            'portfolio_rebalancing' => '0',
            'retirement_planning' => '0',
            'automatic_deposits' => '1',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '0',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '0',
            'access_platforms' => null,
            'two_factor_auth' => '0',
            'customer_service' => null,
            'number_accounts' => null,
            'average_account_size' => null,
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => '900 Middlefield Rd., Redwood City, CA 94063',
            'founded' => '2008',
            'site_url' => null,
            'phone' => null,
            'ceo' => 'Andy Rachleff',
            'contact_details' => 'Clearing Agency: RBC | FINRA',
            'is_active' => '0',
            'ratings' => [
                 'commissions' => '9.00',
                'service' => '9.00',
                'comfortable' => '8.00',
                'tools' => '8.50',
                'investment_options' => '8.50',
                'asset_allocation' => '9.00',
                'total' => '8.67',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRUSTS']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['NON_PROFIT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['529']['id'],
            ],
        ],
        'BETTERMENT' => [
            'name' => 'Betterment',
            'logo' => '/files/betterment-review.png',
            'title' => 'Betterment Review 2018 – Making Investing Simple',
            'short_description' => "<p>Betterment is equally a good starting point for beginning investors and a useful platform for more experienced investors. The robo advisor has no minimum deposit and costs 0.25% annually. If you need the assistance, it recently added human advisors who can assist with your retirement account. Unfortunately, Betterment&#39;s asset allocation excludes REITs or commodities.</p>",
            'description' => null,
            'referral_link' => null,
            'video_link' => null,
            'minimum_account' => '0',
            'management_fee' => '0.15',
            'fee_details' => 'Digital – 0.15-0.25%/year; Premium – 0.30-0.40%/year',
            'aum' => '14142614130',
            'promotions' => 'Up To 1 Year Free',
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '1',
            'tax_loss' => '0',
            'tax_loss_details' => null,
            'portfolio_rebalancing' => '0',
            'retirement_planning' => '0',
            'automatic_deposits' => '0',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '0',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '0',
            'access_platforms' => null,
            'two_factor_auth' => '0',
            'customer_service' => null,
            'number_accounts' => null,
            'average_account_size' => null,
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => null,
            'founded' => '2008',
            'site_url' => null,
            'phone' => null,
            'ceo' => null,
            'contact_details' => null,
            'is_active' => '0',
            'ratings' => [
                'commissions' => '8.00',
                'service' => '9.00',
                'comfortable' => '9.00',
                'tools' => '9.00',
                'investment_options' => '9.00',
                'asset_allocation' => '8.50',
                'total' => '8.75',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRUSTS']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['NON_PROFIT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
            ],
        ],
        'SOFI' => [
            'name' => 'SoFi',
            'logo' => '/files/sofi-wealth-management-review.png',
            'title' => 'SoFi Wealth Review 2018 – A Low-Cost Robo Advisor for Millennials',
            'short_description' => "<p>SoFi Wealth is an investment management service that combines robo investing with access to a human financial advisor. Accounts are free for SoFi borrowers and those with a portfolio below $10,000. SoFi Wealth focuses only on index fund investments to meet your financial goals, and you won&#39;t find tax loss harvesting.</p>",
            'description' => null,
            'referral_link' => 'https://www.sofi.com/wealth-management/',
            'video_link' => null,
            'minimum_account' => '100',
            'management_fee' => '0.15',
            'fee_details' => 'Digital – 0.15-0.25%/year; Premium – 0.30-0.40%/year',
            'aum' => '43461313',
            'promotions' => null,
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '0',
            'tax_loss' => '0',
            'tax_loss_details' => null,
            'portfolio_rebalancing' => '0',
            'retirement_planning' => '0',
            'automatic_deposits' => '0',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '0',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '0',
            'access_platforms' => null,
            'two_factor_auth' => '0',
            'customer_service' => null,
            'number_accounts' => null,
            'average_account_size' => null,
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => null,
            'founded' => '2011',
            'site_url' => null,
            'phone' => null,
            'ceo' => null,
            'contact_details' => null,
            'is_active' => '0',
            'ratings' => [
                'commissions' => '9.50',
                'service' => '9.00',
                'comfortable' => '9.50',
                'tools' => '8.00',
                'investment_options' => '7.50',
                'asset_allocation' => '8.00',
                'total' => '8.58',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
            ],
        ],
        'WEALTHSIMPLE' => [
            'name' => 'Wealthsimple',
            'logo' => '/files/wealthsimple-review.png',
            'title' => 'Wealthsimple Review 2018 – Automated Investing With Human Advice',
            'short_description' => "<p>Wealthsimple is a solid addition to the current slate of robo advisors available. The service offers a socially responsible investment option, as well as assistance from a live representative. However, compared to other firms their fees are on the high side.</p>",
            'description' => null,
            'referral_link' => 'https://investorjunkie.com/go/wealthsimple-compare1',
            'video_link' => null,
            'minimum_account' => '0',
            'management_fee' => '0.50',
            'fee_details' => '$0 to $100k – 0.50%/year; $100k+ – 0.40%/year',
            'aum' => '52233132',
            'promotions' => 'Up to $100 Bonus',
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '1',
            'tax_loss' => '1',
            'tax_loss_details' => 'All Taxable Accounts',
            'portfolio_rebalancing' => '1',
            'retirement_planning' => '0',
            'automatic_deposits' => '1',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '1',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '1',
            'access_platforms' => 'Website, iOS App, Apple Watch, Android App',
            'two_factor_auth' => '0',
            'customer_service' => null,
            'number_accounts' => '9467',
            'average_account_size' => '5517',
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => '860 Richmond St. W., Toronto M6J 1C9',
            'founded' => '2014',
            'site_url' => null,
            'phone' => null,
            'ceo' => 'Michael Katchen',
            'contact_details' => null,
            'is_active' => '0',
            'ratings' => [
                'commissions' => '7.00',
                'service' => '8.50',
                'comfortable' => '8.50',
                'tools' => '8.00',
                'investment_options' => '8.00',
                'asset_allocation' => '8.00',
                'total' => '8.00',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRUSTS']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
            ],
        ],
        'M1_FINANCE' => [
            'name' => 'M1 Finance',
            'logo' => '/files/m1-finance-review.png',
            'title' => 'M1 Finance Review 2018 – A Robo Advisor and Brokerage Hybrid',
            'short_description' => "<p>Combining the best of both traditional investment brokerage accounts and robo advisors, M1 Finance is dangerously close to being the perfect all-around investment platform. The only significant negatives are that it does not offer tax-loss harvesting or investment in mutual funds.</p>",
            'description' => null,
            'referral_link' => 'https://www.m1finance.com/?utm_campaign=31834&utm_medium=ambassador&mbsy_source=bebe17e5-5ea0-4465-9a53-420efe39cdd6&campaignid=31834&mbsy=hTr8b&utm_source=hTr8b',
            'video_link' => null,
            'minimum_account' => '0',
            'management_fee' => null,
            'fee_details' => null,
            'aum' => '100000000',
            'promotions' => 'Invest for FREE',
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '0',
            'tax_loss' => '0',
            'tax_loss_details' => null,
            'portfolio_rebalancing' => '1',
            'retirement_planning' => '0',
            'automatic_deposits' => '1',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '1',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '1',
            'access_platforms' => 'Website, iOS App, Android App',
            'two_factor_auth' => '0',
            'customer_service' => 'Phone: M-F 9A-5P CT; Email',
            'number_accounts' => '25000',
            'average_account_size' => '4000',
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => '213 W. Institute Pl., Suite 301, Chicago, IL 60610',
            'founded' => '2015',
            'site_url' => null,
            'phone' => null,
            'ceo' => 'Brian Barnes',
            'contact_details' => null,
            'is_active' => '0',
            'ratings' => [
                'commissions' => '10.00',
                'service' => '7.00',
                'comfortable' => '9.00',
                'tools' => '7.50',
                'investment_options' => '9.50',
                'asset_allocation' => '9.00',
                'total' => '8.67',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRUSTS']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
            ],
        ],
        'VPAS' => [
            'name' => 'Vanguard Personal Advisor Services',
            'logo' => '/files/vanguard-review.png',
            'title' => 'Vanguard Personal Advisor Services Review 2018 – Low-Cost, Personal Service',
            'short_description' => "<p>A solid entry into the robo advisor space, Vanguard Personal Advisor Services is backed by the trusted Vanguard brand and features real, live human advisors you can call. Unfortunately, the service requires a hefty $50k deposit, which excludes many beginning investors.</p>",
            'description' => null,
            'referral_link' => 'https://investor.vanguard.com/advice/personal-advisor',
            'video_link' => null,
            'minimum_account' => '50000',
            'management_fee' => '0.30',
            'fee_details' => null,
            'aum' => null,
            'promotions' => null,
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '1',
            'tax_loss' => '0',
            'tax_loss_details' => null,
            'portfolio_rebalancing' => '1',
            'retirement_planning' => '0',
            'automatic_deposits' => '1',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '0',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '0',
            'access_platforms' => 'Website, iOS App, Android App',
            'two_factor_auth' => '0',
            'customer_service' => 'Phone M-F 8A-8P ET; Email M-F',
            'number_accounts' => null,
            'average_account_size' => null,
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => '100 Vanguard Blvd., Malvern, PA 19355',
            'founded' => '1975',
            'site_url' => null,
            'phone' => null,
            'ceo' => 'Tim Buckley',
            'contact_details' => null,
            'is_active' => '0',
            'ratings' => [
                'commissions' => '8.50',
                'service' => '7.50',
                'comfortable' => '7.00',
                'tools' => '6.50',
                'investment_options' => '9.50',
                'asset_allocation' => '8.00',
                'total' => '7.83',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SIMPLE_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRUSTS']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
            ],
        ],
        'MEGI' => [
            'name' => 'Merrill Edge Guided Investing (MEGI)',
            'logo' => '/files/megi-review.png',
            'title' => 'Merrill Edge Guided Investing (MEGI) Review 2018 – Merrill Lynch Enters the Robo Advisor Space',
            'short_description' => "<p>MEGI is a robo advisor that combines automated investing with active management of your portfolio. It invests your money in index-based ETFs, but it actively manages your portfolio allocation. This gives you an opportunity to both outperform the market and minimize losses in a downturn. The major negative is that the management fee is higher than those of most other robo advisors. But the active management component may very well justify the higher fee.</p>",
            'description' => null,
            'referral_link' => 'https://www.merrilledge.com/cmaoffer?cm_mmc=gwm-edge-inv-_-investorjunkie-_-1x1_na_600.jpg-_-2019_display_merrill_edge_baseline',
            'video_link' => null,
            'minimum_account' => '5000',
            'management_fee' => '0.45',
            'fee_details' => null,
            'aum' => null,
            'promotions' => null,
            'human_advisors' => '0',
            'human_advisors_details' => null,
            'assistance_401k' => '0',
            'tax_loss' => '0',
            'tax_loss_details' => null,
            'portfolio_rebalancing' => '1',
            'retirement_planning' => '0',
            'automatic_deposits' => '1',
            'clearing_agency' => null,
            'self_clearing' => '0',
            'smart_beta' => '0',
            'responsible_investing' => '0',
            'invests_commodities' => '0',
            'real_estate' => '0',
            'fractional_shares' => '0',
            'access_platforms' => 'Website, iOS App, Android App',
            'two_factor_auth' => '0',
            'customer_service' => 'Phone: 24/7; Live Chat: 24/7; Email',
            'number_accounts' => null,
            'average_account_size' => null,
            'additional_information' => null,
            'is_verify' => '0',
            'headquarters' => '1 Bryant Park, New York, NY 10036',
            'founded' => '2017',
            'site_url' => null,
            'phone' => null,
            'ceo' => 'Lizbeth Nelle Applebaum',
            'contact_details' => null,
            'is_active' => '0',
            'ratings' => [
                'commissions' => '6.00',
                'service' => '8.50',
                'comfortable' => '8.00',
                'tools' => '10.00',
                'investment_options' => '8.00',
                'asset_allocation' => '8.00',
                'total' => '8.08',
            ],
            'account_types' => [
                AccountTypeSeeder::ACCOUNT_TYPES['TAXABLE']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['TRADITIONAL_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SEP_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SOLO_401(K)']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['JOINT']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROLLOVER_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['SIMPLE_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['ROTH_IRA']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['CUSTODIAL']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['401(K)']['id'],
                AccountTypeSeeder::ACCOUNT_TYPES['529']['id'],
            ],
        ]
    ];

    /**
     * Run the database seeds.
     *
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     * @return void
     */
    public function run()
    {
        // clear tables
        DB::table('robo_advisors')->truncate();
        DB::table('ratings')->truncate();
        DB::table('account_type_robo_advisor')->truncate();
        // create base RoboAdvisors
        $this->createRoboAdvisors();
        // create RoboAdvisors clone
        $this->createRoboAdvisors(true, 5);
    }

    /**
     * @param bool $is_need_recursion
     * @param $max_recursion
     * @param int $recursion_level
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     */
    public function createRoboAdvisors($is_need_recursion = false, $max_recursion = 0, $recursion_level = 1)
    {
        foreach (self::ROBO_ADVISORS as $robo_advisor) {
            $this->robo_advisor_iteration++;
            $logo = '';
            $filesystem = new Filesystem();
            $path = __DIR__ . $robo_advisor['logo'];
            if ($filesystem->exists($path)) {
                $file_name = $this->robo_advisor_iteration. time() . '-' . $filesystem->basename($path);
                $file_content = $filesystem->get($path);
                Storage::disk('public')->put($file_name,  $file_content);
                $logo = $file_name;
            }
            $name = $is_need_recursion ? $robo_advisor['name'].'_(copy-'.$recursion_level.')':$robo_advisor['name'];
            DB::table('robo_advisors')->insert([
                'id' => $this->robo_advisor_iteration,
                'name' => $name,
                'logo' => $logo,
                'title' => $robo_advisor['title'],
                'short_description' => $robo_advisor['short_description'],
                'description' => $robo_advisor['description'],
                'referral_link' => $robo_advisor['referral_link'],
                'video_link' => $robo_advisor['video_link'],
                'minimum_account' => $robo_advisor['minimum_account'],
                'management_fee' => $robo_advisor['management_fee'],
                'fee_details' => $robo_advisor['fee_details'],
                'aum' => $robo_advisor['aum'],
                'promotions' => $robo_advisor['promotions'],
                'human_advisors' => $robo_advisor['human_advisors'],
                'human_advisors_details' => $robo_advisor['human_advisors_details'],
                'assistance_401k' => $robo_advisor['assistance_401k'],
                'tax_loss' => $robo_advisor['tax_loss'],
                'tax_loss_details' => $robo_advisor['tax_loss_details'],
                'portfolio_rebalancing' => $robo_advisor['portfolio_rebalancing'],
                'retirement_planning' => $robo_advisor['retirement_planning'],
                'automatic_deposits' => $robo_advisor['automatic_deposits'],
                'clearing_agency' => $robo_advisor['clearing_agency'],
                'self_clearing' => $robo_advisor['self_clearing'],
                'smart_beta' => $robo_advisor['smart_beta'],
                'responsible_investing' => $robo_advisor['responsible_investing'],
                'invests_commodities' => $robo_advisor['invests_commodities'],
                'real_estate' => $robo_advisor['real_estate'],
                'fractional_shares' => $robo_advisor['fractional_shares'],
                'access_platforms' => $robo_advisor['access_platforms'],
                'two_factor_auth' => $robo_advisor['two_factor_auth'],
                'customer_service' => $robo_advisor['customer_service'],
                'number_accounts' => $robo_advisor['number_accounts'],
                'average_account_size' => $robo_advisor['average_account_size'],
                'additional_information' => $robo_advisor['additional_information'],
                'is_verify' => $robo_advisor['is_verify'],
                'headquarters' => $robo_advisor['headquarters'],
                'founded' => $robo_advisor['founded'],
                'site_url' => $robo_advisor['site_url'],
                'phone' => $robo_advisor['phone'],
                'ceo' => $robo_advisor['ceo'],
                'contact_details' => $robo_advisor['contact_details'],
                'is_active' => $robo_advisor['is_active'],
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ]);
            DB::table('ratings')->insert([
                'id' => $this->robo_advisor_iteration,
                'commissions' => $robo_advisor['ratings']['commissions'],
                'service' => $robo_advisor['ratings']['service'],
                'comfortable' => $robo_advisor['ratings']['comfortable'],
                'tools' => $robo_advisor['ratings']['tools'],
                'investment_options' => $robo_advisor['ratings']['investment_options'],
                'asset_allocation' => $robo_advisor['ratings']['asset_allocation'],
                'total' => $robo_advisor['ratings']['total'],
                'robo_advisor_id' => $this->robo_advisor_iteration,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ]);
            foreach ($robo_advisor['account_types'] as $account_type_id) {
                $this->account_type_iteration++;
                DB::table('account_type_robo_advisor')->insert([
                    'id' => $this->account_type_iteration,
                    'account_type_id' => $account_type_id,
                    'robo_advisor_id' => $this->robo_advisor_iteration,
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ]);
            }
        }

        if ($is_need_recursion && $recursion_level < $max_recursion) {

            $this->createRoboAdvisors($is_need_recursion, $max_recursion, ++$recursion_level);
        }
    }
}
